//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGYM_MS.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashIn
    {
        public System.DateTime Date { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string RecieptID { get; set; }
        public string Price { get; set; }
        public string Desc { get; set; }
        public string TraineeName { get; set; }
        public string Type { get; set; }
        public string userName { get; set; }
        public string OfferName { get; set; }
        public int CashID { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
