//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGYM_MS.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duration
    {
        public Duration()
        {
            this.Offers = new HashSet<Offer>();
        }
    
        public int DurationID { get; set; }
        public string DurationName { get; set; }
    
        public virtual ICollection<Offer> Offers { get; set; }
    }
}
