//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGYM_MS.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmployeesDailies = new HashSet<EmployeesDaily>();
        }
    
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Gender { get; set; }
        public string Status { get; set; }
        public string Nationality { get; set; }
        public string Degree { get; set; }
        public string NationalID { get; set; }
        public byte[] Photo { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> HiringDate { get; set; }
        public string Telephone { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Mail { get; set; }
        public Nullable<int> JobID { get; set; }
        public string Experience { get; set; }
        public string Type { get; set; }
        public string Salary { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string CardNumber { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual ICollection<EmployeesDaily> EmployeesDailies { get; set; }
    }
}
