//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGYM_MS.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesDaily
    {
        public int EmployeeID { get; set; }
        public System.DateTime DateComing { get; set; }
        public Nullable<System.DateTime> DateLeaving { get; set; }
        public string Hours { get; set; }
        public Nullable<bool> Editable { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
