//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGYM_MS.EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GymEntities1 : DbContext
    {
        public GymEntities1()
            : base("name=GymEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Duration> Durations { get; set; }
        public DbSet<Job> Jobs { get; set; }
        public DbSet<SocialMedia> SocialMedias { get; set; }
        public DbSet<Interest> Interests { get; set; }
        public DbSet<Invitation> Invitations { get; set; }
        public DbSet<Session> Sessions { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }
        public DbSet<Outcome> Outcomes { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Traffic> Traffic { get; set; }
        public DbSet<Offer> Offers { get; set; }
        public DbSet<EmployeesDaily> EmployeesDailies { get; set; }
        public DbSet<UsersAccess> UsersAccesses { get; set; }
        public DbSet<Login> Logins { get; set; }
        public DbSet<InbodyReport> InbodyReports { get; set; }
        public DbSet<TraineesDaily> TraineesDailies { get; set; }
        public DbSet<Trainee> Trainees { get; set; }
        public DbSet<TraineeProfile> TraineeProfiles { get; set; }
        public DbSet<CashIn> CashIns { get; set; }
        public DbSet<GymData> GymDatas { get; set; }
    }
}
