//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGYM_MS.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class InbodyReport
    {
        public int InodyID { get; set; }
        public Nullable<int> LogID { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string BMI { get; set; }
        public string BMR { get; set; }
        public string Fat_ { get; set; }
        public string FatMass { get; set; }
        public string FFM { get; set; }
        public string TBW { get; set; }
        public string VFHDR { get; set; }
        public string FAT__ { get; set; }
        public string FatMass_ { get; set; }
        public string WholeBody { get; set; }
        public string RightLeg { get; set; }
        public string LeftLeg { get; set; }
        public string RightArm { get; set; }
        public string LeftArm { get; set; }
        public string RightLegFat_ { get; set; }
        public string RightLegFatMass { get; set; }
        public string RightLegFFM { get; set; }
        public string RightLegMuscle { get; set; }
        public string LeftLegFat_ { get; set; }
        public string LeftLegFatMass { get; set; }
        public string LeftLegFFM { get; set; }
        public string LeftLegMuscle { get; set; }
        public string RightArmFat_ { get; set; }
        public string RightArmFatMass { get; set; }
        public string RightArmFFM { get; set; }
        public string RightArmMuscle { get; set; }
        public string LeftArmFat_ { get; set; }
        public string LeftArmFatMass { get; set; }
        public string LeftArmFFM { get; set; }
        public string LeftArmMuscle { get; set; }
        public string TrunkFat_ { get; set; }
        public string TrunkFatMass { get; set; }
        public string TrunkFFM { get; set; }
        public string TrunkMuscle { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual TraineeProfile TraineeProfile { get; set; }
    }
}
