//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGYM_MS.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interest
    {
        public int InterestID { get; set; }
        public Nullable<bool> Aerobics { get; set; }
        public Nullable<bool> Running { get; set; }
        public Nullable<bool> Swimming { get; set; }
        public Nullable<bool> PersonalTraining { get; set; }
        public Nullable<bool> Rohabilitation { get; set; }
        public Nullable<bool> Fitness { get; set; }
        public Nullable<bool> WeightGaining { get; set; }
        public Nullable<bool> WeightLoss { get; set; }
        public Nullable<bool> Mas { get; set; }
        public Nullable<bool> BodyBuilding { get; set; }
        public Nullable<bool> Spa { get; set; }
        public Nullable<bool> Other { get; set; }
        public Nullable<int> InvitationID { get; set; }
    
        public virtual Invitation Invitation { get; set; }
    }
}
