//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGYM_MS.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitation
    {
        public Invitation()
        {
            this.Interests = new HashSet<Interest>();
        }
    
        public int InvitationID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> TraineeID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> SessionID { get; set; }
        public string Price { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Interest> Interests { get; set; }
        public virtual Session Session { get; set; }
    }
}
