//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGYM_MS.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public Offer()
        {
            this.TraineeProfiles = new HashSet<TraineeProfile>();
        }
    
        public int OfferID { get; set; }
        public string OfferName { get; set; }
        public int DurationID { get; set; }
        public string Price { get; set; }
        public string Type { get; set; }
        public Nullable<int> SessionsNum { get; set; }
        public Nullable<int> Freezing { get; set; }
        public Nullable<int> Invitations { get; set; }
        public Nullable<int> SPA { get; set; }
        public Nullable<int> Inbody { get; set; }
        public Nullable<int> Massage { get; set; }
        public Nullable<int> Others { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public Nullable<bool> frozen { get; set; }
    
        public virtual Duration Duration { get; set; }
        public virtual ICollection<TraineeProfile> TraineeProfiles { get; set; }
    }
}
