//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGYM_MS.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialMedia
    {
        public SocialMedia()
        {
            this.Trainees = new HashSet<Trainee>();
        }
    
        public int SocialID { get; set; }
        public string Name { get; set; }
        public Nullable<int> number { get; set; }
    
        public virtual ICollection<Trainee> Trainees { get; set; }
    }
}
