//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGYM_MS.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traffic
    {
        public System.DateTime DayDate { get; set; }
        public Nullable<double> TotalIncome { get; set; }
        public Nullable<double> TotalOutcome { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
