//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGYM_MS.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainee
    {
        public Trainee()
        {
            this.TraineesDailies = new HashSet<TraineesDaily>();
            this.TraineeProfiles = new HashSet<TraineeProfile>();
        }
    
        public int TraineeID { get; set; }
        public string TraineeName { get; set; }
        public Nullable<System.DateTime> Birtdate { get; set; }
        public string Gender { get; set; }
        public string Status { get; set; }
        public string Nationality { get; set; }
        public string Degree { get; set; }
        public string NationalID { get; set; }
        public byte[] Photo { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string Telephone { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Mail { get; set; }
        public Nullable<int> SocialID { get; set; }
        public string CardNumber { get; set; }
    
        public virtual SocialMedia SocialMedia { get; set; }
        public virtual ICollection<TraineesDaily> TraineesDailies { get; set; }
        public virtual ICollection<TraineeProfile> TraineeProfiles { get; set; }
    }
}
