//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGYM_MS.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraineeProfile
    {
        public TraineeProfile()
        {
            this.InbodyReports = new HashSet<InbodyReport>();
            this.TraineesDailies = new HashSet<TraineesDaily>();
        }
    
        public int LogID { get; set; }
        public Nullable<int> TraineeID { get; set; }
        public Nullable<int> OfferID { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Paid { get; set; }
        public Nullable<double> Carry { get; set; }
        public string PaymentMethod { get; set; }
        public string Type { get; set; }
        public Nullable<int> SessionsNum { get; set; }
        public Nullable<int> Freezing { get; set; }
        public Nullable<int> Invitations { get; set; }
        public Nullable<int> Inbody { get; set; }
        public Nullable<int> SPA { get; set; }
        public Nullable<int> Massage { get; set; }
        public Nullable<int> Others { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Frozen { get; set; }
        public Nullable<bool> Canceled { get; set; }
        public Nullable<bool> Transfered { get; set; }
        public Nullable<int> TrainerID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual ICollection<InbodyReport> InbodyReports { get; set; }
        public virtual Offer Offer { get; set; }
        public virtual Trainee Trainee { get; set; }
        public virtual ICollection<TraineesDaily> TraineesDailies { get; set; }
    }
}
