//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGYM_MS.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersAccess
    {
        public int UserID { get; set; }
        public Nullable<bool> AddNewTrainee { get; set; }
        public Nullable<bool> SearchMen { get; set; }
        public Nullable<bool> SearchWomen { get; set; }
        public Nullable<bool> AddOffer { get; set; }
        public Nullable<bool> EditOffer { get; set; }
        public Nullable<bool> ShowTrainees { get; set; }
        public Nullable<bool> CancelTraineeProfile { get; set; }
        public Nullable<bool> AddIncomeOutCome { get; set; }
        public Nullable<bool> Settings { get; set; }
        public Nullable<bool> EditTraineeProfile { get; set; }
        public Nullable<bool> Reports { get; set; }
        public Nullable<bool> NewIncomeOutCome { get; set; }
        public Nullable<bool> AddNewUser { get; set; }
        public Nullable<bool> EditUsers { get; set; }
        public Nullable<bool> DeleteTrainee { get; set; }
        public Nullable<bool> FreezeTrainee { get; set; }
    
        public virtual User User { get; set; }
    }
}
